---
config:
  radar:
    curveTension: 0.15
    axisScaleFactor: 0.2
  themeVariables:
    cScale0: "#FF0000"
    cScale1: "#00CC00"
    cScale2: "#0000FF "
    cScale3: "#009999 "
    radar:
      curveOpacity: 0.1
id: c52ac12f-eb54-4a17-9739-6dcaabd8d4f7
---
radar-beta
    axis a["Tikslumas"]
    axis p["Preciziškumas"], r["Atkūrimas"], f["F1"]
    curve e1["E1"]{59.2, 73.9, 59.2, 59.2}
    curve e2["E2"]{72.4, 79.1, 72.4, 73.2}
    curve e3["E3"]{63.4, 60, 63.4, 60.7}
    curve e4["E4"]{79.4, 79.6, 79.4, 79.5}

  max 85
  min 50
  %% graticule polygon